function FileData_Pairs(x)
{
x.t("library","consists");
x.t("2008","2012");
x.t("scalable","network");
x.t("describes","features");
x.t("layer","models");
x.t("sections","packet");
x.t("consists","following");
x.t("network","technologies");
x.t("features","configuration");
x.t("traffic","generator");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("phone","call");
x.t("umts","model");
x.t("2012","scalable");
x.t("chapter","describes");
x.t("scenarios","application");
x.t("configuration","requirements");
x.t("generator","2008");
x.t("models","umts");
x.t("models","chapter");
x.t("models","application");
x.t("application","layer");
x.t("applications","phone");
x.t("packet","service");
x.t("call","traffic");
x.t("model","library");
x.t("following","sections");
x.t("service","applications");
x.t("statistics","scenarios");
}
