function FileData_Pairs(x)
{
x.t("2008","2012");
x.t("scalable","network");
x.t("describes","features");
x.t("layer","models");
x.t("consists","following");
x.t("network","technologies");
x.t("features","configuration");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("2012","scalable");
x.t("chapter","describes");
x.t("section","802.16");
x.t("scenarios","phy");
x.t("configuration","requirements");
x.t("models","consists");
x.t("models","chapter");
x.t("models","phy");
x.t("phy","2008");
x.t("phy","layer");
x.t("following","section");
x.t("statistics","scenarios");
x.t("802.16","phy");
}
