function FileData_Pairs(x)
{
x.t("2008","2012");
x.t("scalable","network");
x.t("mobile","communications");
x.t("network","technologies");
x.t("3.3","supplemental");
x.t("none","2008");
x.t("supplemental","information");
x.t("communications","(gsm)");
x.t("2012","scalable");
x.t("information","3.3");
x.t("information","none");
x.t("information","global");
x.t("global","system");
x.t("(gsm)","model");
x.t("system","mobile");
x.t("model","3.3");
}
