function FileData_Pairs(x)
{
x.t("library","consists");
x.t("2008","2012");
x.t("scalable","network");
x.t("describes","features");
x.t("layer","models");
x.t("networks","model");
x.t("consists","following");
x.t("network","technologies");
x.t("features","configuration");
x.t("requirements","parameters");
x.t("zigbee","application");
x.t("parameters","statistics");
x.t("2012","scalable");
x.t("chapter","describes");
x.t("section","zigbee");
x.t("scenarios","application");
x.t("configuration","requirements");
x.t("models","chapter");
x.t("models","sensor");
x.t("models","application");
x.t("sensor","networks");
x.t("application","2008");
x.t("application","layer");
x.t("model","library");
x.t("following","section");
x.t("statistics","scenarios");
}
