function FileData_Pairs(x)
{
x.t("2008","2012");
x.t("scalable","network");
x.t("describes","features");
x.t("consists","following");
x.t("network","technologies");
x.t("features","configuration");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("on-demand","multicast");
x.t("2012","scalable");
x.t("chapter","describes");
x.t("section","on-demand");
x.t("scenarios","multicast");
x.t("multicast","routing");
x.t("configuration","requirements");
x.t("models","consists");
x.t("models","chapter");
x.t("models","multicast");
x.t("routing","protocol");
x.t("protocol","models");
x.t("protocol","(odmrp)");
x.t("following","section");
x.t("statistics","scenarios");
x.t("(odmrp)","2008");
}
