function FileData_Pairs(x)
{
x.t("2008","2012");
x.t("scalable","network");
x.t("describes","features");
x.t("sections","file-based");
x.t("mobility","models");
x.t("mobility","model");
x.t("consists","following");
x.t("group","node");
x.t("network","technologies");
x.t("features","configuration");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("placement","mobility");
x.t("random","waypoint");
x.t("2012","scalable");
x.t("chapter","describes");
x.t("node","placement");
x.t("scenarios","mobility");
x.t("configuration","requirements");
x.t("models","mobility");
x.t("models","consists");
x.t("models","random");
x.t("models","chapter");
x.t("file-based","mobility");
x.t("following","sections");
x.t("model","2008");
x.t("model","group");
x.t("statistics","scenarios");
x.t("waypoint","mobility");
}
