function FileData_Pairs(x)
{
x.t("real-time","transfer");
x.t("protocols","real-time");
x.t("protocols","session");
x.t("internet","protocol");
x.t("2008","2012");
x.t("multimedia","applications");
x.t("scalable","network");
x.t("describes","features");
x.t("(sip)","voice");
x.t("(voip)","2008");
x.t("sections","h323");
x.t("consists","following");
x.t("network","technologies");
x.t("features","configuration");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("session","initiation");
x.t("h225","protocols");
x.t("voice","internet");
x.t("2012","scalable");
x.t("chapter","describes");
x.t("scenarios","multimedia");
x.t("configuration","requirements");
x.t("h323","h225");
x.t("initiation","protocol");
x.t("transfer","protocols");
x.t("protocol","(sip)");
x.t("protocol","(voip)");
x.t("applications","multimedia");
x.t("applications","consists");
x.t("applications","chapter");
x.t("following","sections");
x.t("statistics","scenarios");
}
