function FileData_Pairs(x)
{
x.t("label","switching");
x.t("extensions","ospf");
x.t("(diffserv)","multi-protocol");
x.t("2008","2012");
x.t("scalable","network");
x.t("describes","features");
x.t("differentiated","services");
x.t("qos","models");
x.t("(qospf)","2008");
x.t("sections","differentiated");
x.t("consists","following");
x.t("network","technologies");
x.t("features","configuration");
x.t("(qos)","models");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("switching","(mpls)");
x.t("quality","service");
x.t("2012","scalable");
x.t("chapter","describes");
x.t("ospf","(qospf)");
x.t("scenarios","qos");
x.t("(mpls)","quality");
x.t("configuration","requirements");
x.t("models","consists");
x.t("models","quality");
x.t("models","chapter");
x.t("services","(diffserv)");
x.t("multi-protocol","label");
x.t("service","extensions");
x.t("service","(qos)");
x.t("following","sections");
x.t("statistics","scenarios");
}
