function FileData_Pairs(x)
{
x.t("2008","2012");
x.t("scalable","network");
x.t("describes","features");
x.t("layer","models");
x.t("ethernet","virtual");
x.t("sections","detailed");
x.t("mac","layer");
x.t("consists","following");
x.t("network","technologies");
x.t("features","configuration");
x.t("requirements","parameters");
x.t("virtual","lan");
x.t("parameters","statistics");
x.t("2012","scalable");
x.t("(vlan)","2008");
x.t("chapter","describes");
x.t("detailed","switch");
x.t("switch","model");
x.t("scenarios","mac");
x.t("configuration","requirements");
x.t("models","mac");
x.t("models","consists");
x.t("models","chapter");
x.t("switched","ethernet");
x.t("following","sections");
x.t("model","switched");
x.t("statistics","scenarios");
x.t("lan","(vlan)");
}
