function FileData_Pairs(x)
{
x.t("properties","editors");
x.t("editors","2008");
x.t("2008","2012");
x.t("scalable","network");
x.t("interface","used");
x.t("text","box");
x.t("toolbars","architect");
x.t("network","technologies");
x.t("box","toolbars");
x.t("search","text");
x.t("search","specific");
x.t("accessed","using");
x.t("manuals","online");
x.t("2012","scalable");
x.t("keyword","search");
x.t("architect","properties");
x.t("specific","topics");
x.t("online","manuals");
x.t("online","help");
x.t("help","interface");
x.t("help","accessed");
x.t("help","online");
x.t("documented","online");
x.t("topics","documented");
x.t("used","search");
x.t("using","keyword");
}
