function FileData_Pairs(x)
{
x.t("library","consists");
x.t("2008","2012");
x.t("scalable","network");
x.t("describes","features");
x.t("layer","models");
x.t("consists","following");
x.t("network","technologies");
x.t("features","configuration");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("2012","scalable");
x.t("chapter","describes");
x.t("section","lte");
x.t("scenarios","phy");
x.t("configuration","requirements");
x.t("models","chapter");
x.t("models","phy");
x.t("models","lte");
x.t("phy","layer");
x.t("phy","model");
x.t("lte","phy");
x.t("lte","model");
x.t("model","library");
x.t("model","2008");
x.t("following","section");
x.t("statistics","scenarios");
}
