function FileData_Pairs(x)
{
x.t("library","consists");
x.t("(epc)","model");
x.t("2008","2012");
x.t("scalable","network");
x.t("describes","features");
x.t("layer","models");
x.t("consists","following");
x.t("network","layer");
x.t("network","technologies");
x.t("features","configuration");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("2012","scalable");
x.t("chapter","describes");
x.t("section","(s)");
x.t("scenarios","network");
x.t("configuration","requirements");
x.t("core","packet");
x.t("models","network");
x.t("models","chapter");
x.t("models","lte");
x.t("(s)","lte");
x.t("lte","model");
x.t("lte","evolved");
x.t("packet","(epc)");
x.t("model","library");
x.t("model","2008");
x.t("following","section");
x.t("evolved","core");
x.t("statistics","scenarios");
}
