function FileData_Pairs(x)
{
x.t("coding","guidelines");
x.t("arise","developing");
x.t("interfaces","2008");
x.t("appendix","provides");
x.t("2008","2012");
x.t("lists","issues");
x.t("intended","work");
x.t("scalable","network");
x.t("multiprocessor","(parallel)");
x.t("platforms","coding");
x.t("platforms","appendix");
x.t("external","interfaces");
x.t("network","technologies");
x.t("multi-processor","platforms");
x.t("guidelines","multi-processor");
x.t("guidelines","developing");
x.t("provides","coding");
x.t("developing","parallel-safe");
x.t("developing","models");
x.t("issues","arise");
x.t("2012","scalable");
x.t("section","b.1");
x.t("section","b.2");
x.t("parallel-safe","models");
x.t("(parallel)","architecture");
x.t("b.1","gives");
x.t("b.2","lists");
x.t("architecture","section");
x.t("gives","general");
x.t("models","intended");
x.t("models","section");
x.t("models","run");
x.t("correctly","multiprocessor");
x.t("work","external");
x.t("run","correctly");
x.t("general","guidelines");
}
