function FileData_Pairs(x)
{
x.t("protocols","appendix");
x.t("protocols","inter-simulation");
x.t("protocols","used");
x.t("appendix","describes");
x.t("2008","2012");
x.t("intended","programmers");
x.t("scalable","network");
x.t("describes","details");
x.t("interface","simulator");
x.t("details","protocols");
x.t("want","interface");
x.t("simulator","qualnet");
x.t("network","technologies");
x.t("communication","protocols");
x.t("communication","intended");
x.t("2012","scalable");
x.t("dis","2008");
x.t("hla","dis");
x.t("qualnet","using");
x.t("programmers","want");
x.t("inter-simulation","communication");
x.t("used","inter-simulation");
x.t("using","hla");
}
