function FileData_Pairs(x)
{
x.t("2008","2012");
x.t("scalable","network");
x.t("describes","features");
x.t("consists","following");
x.t("network","technologies");
x.t("features","configuration");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("rough","earth");
x.t("earth","model");
x.t("2012","scalable");
x.t("chapter","describes");
x.t("section","terrain");
x.t("scenarios","propagation");
x.t("configuration","requirements");
x.t("terrain","integrated");
x.t("models","consists");
x.t("models","chapter");
x.t("models","propagation");
x.t("propagation","models");
x.t("(tirem)","2008");
x.t("following","section");
x.t("model","(tirem)");
x.t("statistics","scenarios");
x.t("integrated","rough");
}
