function FileData_Pairs(x)
{
x.t("2008","2012");
x.t("scalable","network");
x.t("describes","features");
x.t("layer","models");
x.t("(udp)","2008");
x.t("user","datagram");
x.t("sections","abstract");
x.t("consists","following");
x.t("(tcp)","user");
x.t("datagram","protocol");
x.t("network","technologies");
x.t("features","configuration");
x.t("tcp","multicast");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("(mdp)","transmission");
x.t("control","protocol");
x.t("2012","scalable");
x.t("chapter","describes");
x.t("transport","layer");
x.t("transmission","control");
x.t("scenarios","transport");
x.t("abstract","tcp");
x.t("abstract","transmission");
x.t("multicast","dissemination");
x.t("configuration","requirements");
x.t("models","consists");
x.t("models","chapter");
x.t("models","transport");
x.t("protocol","(udp)");
x.t("protocol","(tcp)");
x.t("protocol","(mdp)");
x.t("protocol","abstract");
x.t("dissemination","protocol");
x.t("following","sections");
x.t("statistics","scenarios");
}
