function FileData_Pairs(x)
{
x.t("interfaces","interfaces");
x.t("interfaces","chapter");
x.t("interfaces","developer");
x.t("library","consists");
x.t("2008","2012");
x.t("scalable","network");
x.t("describes","features");
x.t("agi","satellite");
x.t("interface","2008");
x.t("external","interfaces");
x.t("sections","agi");
x.t("consists","following");
x.t("network","technologies");
x.t("features","configuration");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("2012","scalable");
x.t("chapter","describes");
x.t("(stk)","interface");
x.t("scenarios","external");
x.t("configuration","requirements");
x.t("developer","model");
x.t("satellite","toolkit");
x.t("model","library");
x.t("following","sections");
x.t("statistics","scenarios");
x.t("toolkit","(stk)");
}
