function FileData_Pairs(x)
{
x.t("2008","2012");
x.t("scalable","network");
x.t("describes","features");
x.t("static","multicast");
x.t("sections","static");
x.t("consists","following");
x.t("network","technologies");
x.t("features","configuration");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("2012","scalable");
x.t("chapter","describes");
x.t("scenarios","multicast");
x.t("multicast","routing");
x.t("multicast","routes");
x.t("configuration","requirements");
x.t("models","consists");
x.t("models","chapter");
x.t("models","multicast");
x.t("routing","protocol");
x.t("protocol","models");
x.t("following","sections");
x.t("routes","2008");
x.t("statistics","scenarios");
}
