function FileData_Pairs(x)
{
x.t("2008","2012");
x.t("scalable","network");
x.t("describes","features");
x.t("multi-layer","models");
x.t("mode","(atm)");
x.t("sections","asynchronous");
x.t("consists","following");
x.t("network","technologies");
x.t("features","configuration");
x.t("requirements","parameters");
x.t("parameters","statistics");
x.t("2012","scalable");
x.t("chapter","describes");
x.t("(atm)","2008");
x.t("scenarios","multi-layer");
x.t("configuration","requirements");
x.t("models","multi-layer");
x.t("models","consists");
x.t("models","chapter");
x.t("transfer","mode");
x.t("asynchronous","transfer");
x.t("following","sections");
x.t("statistics","scenarios");
}
